FROM python:3.12-slim-bookworm
RUN apt-get update && apt-get install -y git
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY eips_etl /app/eips_etl
COPY eips_exposed /app/eips_exposed
COPY eips_web /app/eips_web
COPY uv.lock /app/
COPY pyproject.toml /app/
COPY manage.py /app/
COPY devops/scripts/update-entrypoint.sh /app/

WORKDIR /app

RUN uv sync --frozen

ENV ASSETS_DIR=/data/assets

ENTRYPOINT ["bash", "./update-entrypoint.sh"]
