---
version: "3"

services:
  postgres:
    restart: always
    image: postgres:10.0
    environment:
      - EIPS_DB_URL=${EIPS_DB_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432/tcp"
    ports:
      - "5432:5432"

  graphql:
    build:
      context: .
      dockerfile: ./ops/dockerfiles/eips_api
    depends_on:
      - postgres
    environment:
      - EIPS_DB_URL=${EIPS_DB_URL}
      - EIPS_SERVER_PORT=8080
      - EIPS_LOCAL_REPO=/tmp/eips
    expose:
      - "8080/tcp"
    ports:
      - "8080:8080"

  processor:
    build:
      context: .
      dockerfile: ./ops/dockerfiles/eips_processor
    depends_on:
      - postgres
      - graphql  # migrations are run there
    environment:
      - EIPS_DB_URL=${EIPS_DB_URL}
      - EIPS_SERVER_PORT=8080
      - EIPS_LOCAL_REPO=/tmp/eips

  frontend:
    build:
      context: .
      dockerfile: ./ops/dockerfiles/eips_frontend
      args:
        GRAPHQL_URL: http://localhost:8080/graphql
    depends_on:
      - graphql
    expose:
      - "5000/tcp"

  nginx:
    image: nginx:mainline
    volumes:
      - ./ops/conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt # 
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
