apiVersion: v1
kind: Service
metadata:
  name: {{ include "typesense-search.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "typesense-search.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8108
      targetPort: 8108
      name: http
