apiVersion: v1
kind: Service
metadata:
  name: {{ include "eips-web.fullname" . }}
  labels:
    {{- include "eips-web.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "eips-web.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
