---

- name: make sure bad deps are not installed
  yum:
    name:
      - python-docker-py
      - docker-compose
    state: absent

- name: install deps
  yum:
    name: 
      - git
      - certbot
      - python2-pip
    state: present
  tags: letsencrypt

- name: install python deps
  pip:
    name: 
      - docker
      - docker-compose

- name: create ~/.bin if necessary
  file:
    path: ~/.bin
    state: directory
    mode: '0700'

- name: create init_selfsigned_certs
  template:
    src: ../templates/init_selfsigned_certs.sh.j2
    dest: ~/.bin/init_selfsigned_certs.sh
    mode: '0755'
  tags: letsencrypt

- name: create init_certbot.sh
  template:
    src: ../templates/init_certbot.sh.j2
    dest: ~/.bin/init_certbot.sh.sh
    mode: '0755'
  tags: letsencrypt

- name: create temporary self-signed certificates for eips.exposed
  shell: "bash ~/.bin/init_selfsigned_certs.sh {{ item }}"
  tags: letsencrypt
  with_items: "{{ letsencrypt_domains }}"

- debug:
    msg: "!!!!!!!!!!!!!!!!!!!!"

- name: clone eips.exposed repository
  git:
    repo: 'https://github.com/mikeshultz/eips.exposed.git'
    dest: "{{ eips_exposed_srcdir }}"
    update: yes

- name: build images and bring up docker containers
  docker_service:
    build: yes
    project_src: "{{ eips_exposed_srcdir }}"
    state: present
    timeout: 30

- name: "get certs from letsencrypt - {{ item }}"
  shell: "bash  ~/.bin/init_certbot.sh {{ item }}"
  tags: letsencrypt
  with_items: "{{ letsencrypt_domains }}"

- name: ensure HTTP access allowed
  firewalld:
    state: enabled
    zone: public
    service: http
    permanent: true

- name: ensure HTTPS access allowed
  firewalld:
    state: enabled
    zone: public
    service: https
    permanent: true
